# Generated by Django 3.1.4 on 2022-10-12 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_video_embded_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='embded_video',
        ),
    ]
