# Generated by Django 3.1.4 on 2022-10-12 05:37

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_auto_20221012_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='embded_video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
