# Generated by Django 3.1.4 on 2022-10-12 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_auto_20221012_0537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='embded_video',
        ),
    ]
